version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1111:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./data/mydb.sqlite:/mydb.sqlite
      - ./data/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped